version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db